language: java

sudo: false

jdk: oraclejdk8

script: 
- mvn clean
- mvn install
- mvn cobertura:cobertura

branches:
  only:
  - feature-silk

after_success:
- bash <(curl -s https://codecov.io/bash)
