# THIS CONFIGURATION
name: default
comment: A configuration suitable for most cases
author: Mikel Egana Aranguren

# ALDAPA URIs
INTERNAL_BASE: "urn:aldapa:" # (Quoted due to colons)
PROJECT: ${INTERNAL_BASE}:project:+PROJECT_NAME+

# DOMAIN URIs
BASE: http://opendata.eurohelp.es/

# DOMAIN METADATA URIs
DCAT_CATALOG: ${BASE}catalog/+CATALOG_NAME+
DCAT_DATASET: ${BASE}dataset/+DATASET_NAME+
DCAT_DISTRIBUTION: ${BASE}distribution/+DISTRIBUTION_NAME+

# DOMAIN DATA URIs
RESOURCE: ${BASE}resource/+RESOURCE_NAME+
PROPERTY: ${BASE}property/+PROPERTY_NAME+

